// This file will be auto-generated by Supabase CLI
// Run: pnpm db:types (after setting up your project)

export type Database = {
  pta2: {
    Tables: {
      schools: {
        Row: {
          id: string
          name: string
          address: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          created_at?: string
        }
      }
      classes: {
        Row: {
          id: string
          name: string
          school_id: string
          grade_level: string | null
          teacher_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          school_id: string
          grade_level?: string | null
          teacher_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          school_id?: string
          grade_level?: string | null
          teacher_id?: string | null
          created_at?: string
        }
      }
      parents: {
        Row: {
          id: string
          user_id: string | null
          name: string
          contact_number: string | null
          email: string | null
          payment_status: boolean
          payment_date: string | null
          school_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          name: string
          contact_number?: string | null
          email?: string | null
          payment_status?: boolean
          payment_date?: string | null
          school_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          name?: string
          contact_number?: string | null
          email?: string | null
          payment_status?: boolean
          payment_date?: string | null
          school_id?: string
          created_at?: string
        }
      }
      students: {
        Row: {
          id: string
          name: string
          class_id: string
          parent_id: string
          payment_status: boolean
          student_number: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          class_id: string
          parent_id: string
          payment_status?: boolean
          student_number?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          class_id?: string
          parent_id?: string
          payment_status?: boolean
          student_number?: string | null
          created_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          parent_id: string
          amount: number
          category: string
          receipt_url: string | null
          created_by: string
          payment_method: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          parent_id: string
          amount?: number
          category?: string
          receipt_url?: string | null
          created_by: string
          payment_method?: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          parent_id?: string
          amount?: number
          category?: string
          receipt_url?: string | null
          created_by?: string
          payment_method?: string
          notes?: string | null
          created_at?: string
        }
      }
      expenses: {
        Row: {
          id: string
          description: string
          amount: number
          category: string
          receipt_url: string | null
          created_by: string
          school_id: string
          created_at: string
        }
        Insert: {
          id?: string
          description: string
          amount: number
          category: string
          receipt_url?: string | null
          created_by: string
          school_id: string
          created_at?: string
        }
        Update: {
          id?: string
          description?: string
          amount?: number
          category?: string
          receipt_url?: string | null
          created_by?: string
          school_id?: string
          created_at?: string
        }
      }
      user_profiles: {
        Row: {
          id: string
          role: 'parent' | 'teacher' | 'treasurer' | 'principal' | 'admin'
          school_id: string
          full_name: string | null
          created_at: string
        }
        Insert: {
          id: string
          role: 'parent' | 'teacher' | 'treasurer' | 'principal' | 'admin'
          school_id: string
          full_name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: 'parent' | 'teacher' | 'treasurer' | 'principal' | 'admin'
          school_id?: string
          full_name?: string | null
          created_at?: string
        }
      }
    }
  }
}